version: "2"
services:
  db:
    build: ./db
    image: openroads/vn-api-db:latest
    container_name: vn-api-db
    networks:
      - openroads
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=openroads

  api:
    build: .
    image: openroads/vn-api-app:latest
    env_file: .env
    links:
      - db:postgres
    depends_on:
      - db
    ports:
      - "4000:4000"
    networks:
      - openroads
    environment:
      - DATABASE_URL=postgres://postgres@postgres:5432/openroads

  deploy:
    build: .
    command: npm run kes-app-update
    env_file: .env
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

networks:
  openroads:
#networks:
#  default:
#    external:
#      name: openroads
