version: "3"
services:
  db:
    build: ./db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=openroads
  api:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres@postgres:5432/openroads
    links:
      - db:postgres
    ports:
      - "4000:4000"
