version: "2"
services:
  db:
    build: ./db
    image: developmentseed/openroads-vn-db:latest
    container_name: vn-api-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=openroads

  api:
    build: .
    image: developmentseed/openroads-vn-api:latest
    env_file: .env
    depends_on:
      - db
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgres://postgres@db:5432/openroads

  tiler:
    image: developmentseed/openroads-tiler
    env_file: .env
    command: cron.sh
    environment:
      - S3_BUCKET=openroads-vn-tiles
      - S3_TEMPLATE=s3://openroads-vn-tiles/tiles/{z}/{x}/{y}.vector.pbf
      - DATABASE_URL=postgres://postgres@db:5432/openroads

  vn-tiler:
    image: developmentseed/openroads-vn-tiler
    env_file: .env
    command: cron.sh
    environment:
      - S3_BUCKET=openroads-vn-tiles
      - S3_TEMPLATE=s3://openroads-vn-tiles/tiles/{z}/{x}/{y}.vector.pbf
      - DATABASE_URL=postgres://postgres@db:5432/openroads

  deploy:
    image: developmentseed/openroads-vn-api:latest
    command: node_modules/.bin/kes cf update -k aws/app --env-file .env
    env_file: .env
