version: "3"
version: "3"
services:
  db:
    build: ./db
    environment:
      - POSTGRES_DB=openroads
  test-db:
    build: ./db/extensions/test
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=openroads
    depends_on:
      - db
  api:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres@postgres:5432/openroads
    links:
      - db:postgres
    ports:
      - "4000:4000"