version: 2

jobs:
  build:
    #machine: true
    docker:
      - image: docker:17.05.0-ce-git
        environment:
          IMGNAME=developmentseed/openroads-vn-api
    working_dir: ~/project
    steps:
      - restore_cache:
          keys:
            - v0-repo-{{ .Branch }}-{{ .Revision }}
            - v0-repo-{{ .Branch }}
            - v0-repo
      - checkout
      - save_cache:
          key: v0-repo-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/project
      - run:
          name: Creating .env for environment variables
          command: |
            echo "AWS_REGION=$AWS_REGION" >> .env
            echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> .env
            echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> .env
            echo "RDS_USER=$RDS_USER" >> .env
            echo "RDS_PASS=$RDS_PASS" >> .env
      - setup_remote_docker
      #- run:
      #    name: Install dependencies
      #    command: |
      #      apk add --no-cache py-pip=9.0.0-r1
      #      pip install docker-compose==1.16.0
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i ~/project.tar | true
      - run:
          name: Build docker image
          command: docker build --cache-from=project -t $IMGNAME:latest .
      - run:
          name: Save Docker image layer cache
          command: |
            docker save -o ~/project.tar $IMGNAME:latest
      #- run:
      #    name: Run tests
      #    command: |
      #      docker-compose up -d api
          #docker-compose exec api npm test
      - run:
          name: Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              VERSION=$(grep -m1 version package.json | awk -F: '{ print $2 }' | sed 's/[", ]//g')
              docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
              docker tag $IMGNAME:latest $IMGNAME:$VERSION
              docker push $IMGNAME
              docker run --env-file .env $IMGNAME:latest node_modules/.bin/kes cf update -k aws/app
            fi
