version: 2

jobs:
  build:
    #machine: true
    docker:
      - image: docker:17.05.0-ce-git
    working_dir: ~/openroadsvnapi
    steps:
      #- restore_cache:
      #    keys:
      #      - v2-repo-{{ .Branch }}-{{ .Revision }}
      #      - v2-repo-{{ .Branch }}
      #      - v2-repo
      - checkout
      - save_cache:
          key: v2-repo-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/openroadsvnapi
      - run:
          name: Creating .env for environment variables
          command: |
            echo "AWS_REGION=$AWS_REGION" >> .env
            echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> .env
            echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> .env            
            echo "DATABASE_URL=$DATABASE_URL" >> .env
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip=9.0.0-r1
            pip install docker-compose==1.16.0
      #- run:
      #    name: Load Docker image layer cache
      #    command: |
      #      set +o pipefail
      #      docker load -i ~/vn-api-db.tar | true
      #      docker load -i ~/vn-api-app.tar | true
      - run:
          name: Build docker image
          command: docker-compose build
      #- run:
      #    name: Save Docker image layer cache
      #    command: |
      #      docker save -o ~/vn-api-db.tar openroads/vn-api-db:latest
      #      docker save -o ~/vn-api-app.tar openroads/vn-api-app:latest
      - run:
          name: Run tests
          command: |
            docker-compose up -d api
            docker run --env-file .env --network container:db openroads/vn-api-app:latest npm test
      - run:
          name: Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
              docker push openroads/vn-api-db:latest
              docker push openroads/vn-api-app:latest
              docker-compose run deploy
            fi
