stackName: orma

stage: dev

buckets:
  internal: orma-d-deploy

ecs:
  amiid: ami-9d1f7efe
  instanceType: t2.medium
  ecsInstanceProfileArn: arn:aws:iam::552819999234:instance-profile/orma-ecs
  volumeSize: 50
  vpcId: vpc-1dda3b78
  keyPairName: orma
  availabilityZone: '!Sub ${AWS::Region}a'
  maxInstances: 1
  desiredInstances: 1
  services:
    - count: 1
      name: vn
      containers:
        - name: postgres
          image: vn-api-db:latest
          cpu: 100
          memory: 800
          ports:
            - container: 5432
              host: 5433
              protocol: tcp
          envs:
            POSTGRES_DB: openroads
            AWS_DEFAULT_REGION: '!Sub ${AWS::Region}'
            AWS_REGION: '!Sub ${AWS::Region}'

        - name: webapp
          image: vn-api-app:latest
          cpu: 100
          memory: 800
          links:
            - postgres
          envs:
            DATABASE_URL: postgres://postgres@postgres:5432/openroads
            AWS_DEFAULT_REGION: '!Sub ${AWS::Region}'
            AWS_REGION: '!Sub ${AWS::Region}'

        - name: tiler
          image: developmentseed/openroads-tiler
          cpu: 100
          memory: 800
          envs:
            POSTGRES_DB: openroads
            S3_BUCKET: $S3_BUCKET

        - name: tilemap
          image: developmentseed/openroads-tilemap
          cpu: 100
          memory: 800
          ports:
            - container: 8000
              host: 80
              protocol: tcp
          envs:
            S3_BUCKET: $S3_BUCKET

        - name: vn-tiler
          image: developmentseed/openroads-vn-tiler
          cpu: 100
          memory: 800
          envs:
            POSTGRES_DB: openroads
            S3_BUCKET: $S3_BUCKET