stackName: orma

stage: prod

project: openroads-vn

buckets:
  internal: orma-d-deploy

lambdaProcessingRoleArn: {{iamroles.lambdaProcessingRoleArn}}

rds:
  name: openroads
  username: {{RDS_USER}}
  password: {{RDS_PASS}}

ecs:
  amiid: ami-e782f29b
  instanceType: m4.2xlarge
  ecsInstanceProfileArn: arn:aws:iam::552819999234:instance-profile/orma-ecs
  volumeSize: 50
  vpcId: vpc-1dda3b78
  keyPairName: orma
  availabilityZone: '!Sub ${AWS::Region}a'
  maxInstances: 1
  desiredInstances: 1
  services:
    - count: 1
      name: vn
      containers:
        - name: webapp
          image: developmentseed/openroads-vn-api:0.3.0
          cpu: 1024
          memory: 5200
          ports:
            - container: 4000
              host: 80
              protocol: tcp
          envs:
            AWS_DEFAULT_REGION: '!Sub ${AWS::Region}'
            AWS_REGION: '!Sub ${AWS::Region}'
        - name: vn-tiler
          image: developmentseed/openroads-vn-tiler:0.2.2
          cpu: 2048
          memory: 5200
          commands:
            - /opt/app/cron.sh
          envs:
            AWS_ACCESS_KEY_ID: {{AWS_ACCESS_KEY_ID}}
            AWS_SECRET_ACCESS_KEY: {{AWS_SECRET_ACCESS_KEY}}
            MAPBOX_ACCOUNT: {{MAPBOX_ACCOUNT}}
            MAPBOX_ACCESS_TOKEN: {{MAPBOX_ACCESS_TOKEN}}
            S3_TEMPLATE: s3://openroads-vn-tiles-prod/tiles/{z}/{x}/{y}.vector.pbf
            S3_DUMP_BUCKET: openroads-vn-dumps-prod
        - name: tilemap
          image: developmentseed/openroads-tilemap:0.1.1
          cpu: 2048
          memory: 5200
          ports:
            - container: 3000
              host: 3000
              protocol: tcp
          envs:
            BUCKET_URL: https://s3-ap-southeast-1.amazonaws.com/openroads-vn-tiles-prod/tiles


# used as custom resource for cloudformation manipulation
#lambdas:
#- name: CustomBootstrap
#  handler: init-schema.handler
#  timeout: 100
#  memory: 256
#  source: 'db/lambda/init-schema.js'
