stackName: orma

stage: prod

buckets:
  internal: orma-d-deploy

lambdaProcessingRoleArn: {{iamroles.lambdaProcessingRoleArn}}

rds:
  name: openroads
  username: {{RDS_USER}}
  password: {{RDS_PASS}}

ecs:
  amiid: ami-9d1f7efe
  instanceType: t2.medium
  ecsInstanceProfileArn: arn:aws:iam::552819999234:instance-profile/orma-ecs
  volumeSize: 50
  vpcId: vpc-1dda3b78
  keyPairName: orma
  availabilityZone: '!Sub ${AWS::Region}a'
  maxInstances: 1
  desiredInstances: 1
  services:
    - count: 1
      name: vn
      containers:
        - name: webapp
          image: developmentseed/openroads-vn-api:0.2.1
          cpu: 100
          memory: 800
          ports:
            - container: 4000
              host: 80
              protocol: tcp
          envs:
            AWS_DEFAULT_REGION: '!Sub ${AWS::Region}'
            AWS_REGION: '!Sub ${AWS::Region}'
        - name: tiler
          image: developmentseed/openroads-tiler:0.1.0
          cpu: 25
          memory: 500
          commands:
            - /opt/app/cron.sh
          envs:
            S3_TEMPLATE: s3://openroads-vn-tiles/tiles/{z}/{x}/{y}.vector.pbf
        - name: vn-tiler
          image: developmentseed/openroads-vn-tiler:0.1.0
          cpu: 25
          memory: 500
          commands:
            - /opt/app/cron.sh
          envs:
            MAPBOX_ACCOUNT: {{MAPBOX_ACCOUNT}}
            MAPBOX_ACCESS_TOKEN: {{MAPBOX_ACCESS_TOKEN}}
            S3_DUMP_BUCKET: openroads-vn-dumps
            S3_PROPERTIES_BUCKET: openroads-vn-properties
            WHICH_SCRIPT: make-analysis-and-display
        - name: tilemap
          image: developmentseed/openroads-tilemap:0.1.0
          cpu: 50
          memory: 800
          ports:
            - container: 3000
              host: 3000
              protocol: tcp
          envs:
            BUCKET_URL: http://openroads-vn-tiles.s3-website-us-east-1.amazonaws.com/tiles


# used as custom resource for cloudformation manipulation
#lambdas:
#- name: CustomBootstrap
#  handler: init-schema.handler
#  timeout: 100
#  memory: 256
#  source: 'db/lambda/init-schema.js'
